on: [push]

jobs:
  upload-artifact:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: make aritfact
      run: |
        echo hello > /tmp/result.txt
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: result-${{ matrix.os }}
        path: /tmp/result.txt
